### ISSUE TITLE
When post a add show this error - how can i fix this ?

### ISSUE THREAD

**Issue by Lusifar-on** [MrKyr/osclasswizards#1]
Warning: scandir(banner/nodir,banner/nodir): The system cannot find the path specified. (code: 3) in C:\xampp\htdocs\Osclass\oc-content\themes\osclasswizards\functions.php on line 1329

Warning: scandir(banner/nodir): failed to open dir: No such file or directory in C:\xampp\htdocs\Osclass\oc-content\themes\osclasswizards\functions.php on line 1329

Warning: scandir(): (errno 2): No such file or directory in C:\xampp\htdocs\Osclass\oc-content\themes\osclasswizards\functions.php on line 1329

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\Osclass\oc-content\themes\osclasswizards\functions.php on line 1330

**Comment by MrKyr** [comment]
create the folder /httpdocs/osclass/banners/nodir
